const isTopKProvided = Number(process.env.TOP_K_ARTISTS ?? "10")

export const TOP_K_ARTISTS = isNaN(isTopKProvided) ? 10 : isTopKProvided;
export const EASY = "easy";
export const MEDIUM = "medium";
export const HARD = "hard";
export const ARTISTS = [
    "Radiohead",
    "Arctic Monkeys",
    "Muse",
    "The Killers",
    "Nirvana",
    "Foo Fighters",
    "Linkin Park",
    "Placebo",
    "The Smashing Pumpkins",
    "Nine Inch Nails",
    "Coldplay",
    "Imagine Dragons",
    "Paramore",
    "Red Hot Chili Peppers",
    "The Strokes",
    "Queens of the Stone Age",
    "The White Stripes",
    "Interpol",
    "The 1975",
    "Snow Patrol",
    "Kasabian",
    "The Black Keys",
    "Florence + The Machine",
    "Yeah Yeah Yeahs",
    "Editors",
    "The National",
    "Modest Mouse",
    "The Verve",
    "Blur",
    "Oasis",
    "Green Day",
    "Beck",
    "The Cranberries",
    "Evanescence",
    "The Kooks",
    "Franz Ferdinand",
    "Arcade Fire",
    "The Goo Goo Dolls",
    "Smashing Pumpkins",
    "The Libertines",
    "Kings of Leon",
    "Panic! At The Disco",
    "Thirty Seconds to Mars",
    "Death Cab for Cutie",
    "MGMT",
    "Silversun Pickups",
    "Biffy Clyro",
    "R.E.M.",
    "No Doubt",
    "The Offspring",
    "The Cure",
  ];